# Generated by Django 4.2.10 on 2024-02-13 15:14

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, help_text="Your phone", max_length=255, verbose_name="Your phone"),
        ),
        migrations.AddField(
            model_name="user",
            name="registered_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="When user account is registered",
                verbose_name="Registered at",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="uuid",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                help_text="UUID for getting id of users safely",
                verbose_name="UUID",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="website",
            field=models.CharField(
                blank=True,
                help_text="Personal or company website",
                max_length=255,
                verbose_name="Personal or company website",
            ),
        ),
    ]
