# Generated by Django 4.2.10 on 2024-02-15 06:10

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_phone_user_registered_at_user_uuid_user_website"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="credits",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Current credit balance of the user",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Credits",
            ),
        ),
    ]
