# Generated by Django 4.2.10 on 2024-02-18 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_credits"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="total_completion_tokens",
            field=models.IntegerField(
                default=0,
                help_text="Total number of tokens generated in response to the user's prompts across all indexes.",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="total_embedding_operations",
            field=models.IntegerField(
                default=0, help_text="Total number of vectorization operations performed across all indexes."
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="total_prompt_tokens",
            field=models.IntegerField(
                default=0, help_text="Total number of tokens used in the user's prompts across all indexes."
            ),
        ),
    ]
