# Generated by Django 4.2.10 on 2024-02-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_total_completion_tokens_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="total_image_annotations",
            field=models.IntegerField(
                default=0, help_text="Total number of image annotations operations performed across all indexes."
            ),
        ),
    ]
