# Generated by Django 4.2.10 on 2024-02-19 09:08

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_remove_user_credits_user_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="balance",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Current credit balance of the user. It is in micro dollars (1 USD = 1_000_000 micro dollars)",
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
    ]
