# Generated by Django 4.2.10 on 2024-02-17 08:34
from pgvector.django import VectorExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("indexes", "0001_initial"),
    ]

    operations = [VectorExtension()]
