# Generated by Django 4.2.10 on 2024-02-17 15:10

from django.db import migrations, models
import django.db.models.deletion
import pgvector.django
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("indexes", "0002_auto_20240217_1034"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndexNode",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                (
                    "content",
                    models.TextField(help_text="Content of the node, consisting of few sentences from the document."),
                ),
                (
                    "embedding_mini_lm_l6_v2",
                    pgvector.django.VectorField(dimensions=384, help_text="384 sized embedding for MiniLM L6 V2."),
                ),
                (
                    "index_file",
                    models.ForeignKey(
                        help_text="The index file this node is associated with",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nodes",
                        to="indexes.indexfile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Index Node",
                "verbose_name_plural": "Index Nodes",
                "ordering": ["-created"],
            },
        ),
    ]
