# Generated by Django 4.2.10 on 2024-02-17 15:56

from django.db import migrations
import pgvector.django


class Migration(migrations.Migration):

    dependencies = [
        ("indexes", "0003_indexnode"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="indexnode",
            index=pgvector.django.HnswIndex(
                ef_construction=64,
                fields=["embedding_mini_lm_l6_v2"],
                m=16,
                name="mini_lm_vectors_index",
                opclasses=["vector_l2_ops"],
            ),
        ),
    ]
