# Generated by Django 4.2.10 on 2024-02-18 04:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("indexes", "0004_indexnode_mini_lm_vectors_index"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndexQuery",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                (
                    "messages",
                    models.JSONField(default=list, help_text="List of messages exchanged with the assistant."),
                ),
                (
                    "context_node_ids",
                    models.JSONField(default=list, help_text="List of IndexNode IDs used as context for the query."),
                ),
                ("usage", models.JSONField(default=dict, help_text="Details of token usage for the query.")),
                (
                    "index",
                    models.ForeignKey(
                        help_text="Reference to the Index related to this query.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queries",
                        to="indexes.index",
                    ),
                ),
            ],
            options={
                "verbose_name": "Index Query",
                "verbose_name_plural": "Index Queries",
                "ordering": ["-created"],
            },
        ),
    ]
