# Generated by Django 4.2.10 on 2024-02-18 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indexes", "0005_indexquery"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="indexquery",
            name="usage",
        ),
        migrations.AddField(
            model_name="indexquery",
            name="completion_tokens",
            field=models.IntegerField(
                default=0, help_text="Number of tokens generated in response to the user's prompt."
            ),
        ),
        migrations.AddField(
            model_name="indexquery",
            name="prompt_tokens",
            field=models.IntegerField(default=0, help_text="Number of tokens used in the user's prompt."),
        ),
        migrations.AddField(
            model_name="indexquery",
            name="total_tokens",
            field=models.IntegerField(default=0, help_text="Total number of tokens used in this query."),
        ),
    ]
