# Generated by Django 4.2.10 on 2024-02-18 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indexes", "0006_remove_indexquery_usage_indexquery_completion_tokens_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="indexquery",
            name="completion_tokens",
        ),
        migrations.RemoveField(
            model_name="indexquery",
            name="prompt_tokens",
        ),
        migrations.RemoveField(
            model_name="indexquery",
            name="total_tokens",
        ),
        migrations.AddField(
            model_name="index",
            name="completion_tokens",
            field=models.IntegerField(
                default=0, help_text="Number of tokens generated in response to the user's prompt."
            ),
        ),
        migrations.AddField(
            model_name="index",
            name="embedding_operations",
            field=models.IntegerField(default=0, help_text="Number of vectorization operations performed."),
        ),
        migrations.AddField(
            model_name="index",
            name="prompt_tokens",
            field=models.IntegerField(default=0, help_text="Number of tokens used in the user's prompt."),
        ),
    ]
