# Generated by Django 4.2.10 on 2024-02-18 10:58

import django.core.validators
from django.db import migrations, models
import selfgpt.indexes.models


class Migration(migrations.Migration):

    dependencies = [
        ("indexes", "0008_remove_indexnode_mini_lm_vectors_index_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="indexnode",
            name="type",
            field=models.CharField(
                choices=[("text", "Text"), ("image", "Image")],
                default="text",
                help_text="The type of content stored in this node (text or image).",
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="indexfile",
            name="file",
            field=models.FileField(
                help_text="The file uploaded for this index",
                upload_to=selfgpt.indexes.models.get_index_file_location,
                validators=[django.core.validators.FileExtensionValidator(allowed_extensions=["pdf", "txt"])],
            ),
        ),
    ]
