# Generated by Django 4.2.10 on 2024-02-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indexes", "0009_indexnode_type_alter_indexfile_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="index",
            name="image_annotations",
            field=models.IntegerField(default=0, help_text="Number of image annotations performed."),
        ),
    ]
