# Generated by Django 4.2.10 on 2024-03-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indexes", "0011_alter_index_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="indexfile",
            name="type",
            field=models.CharField(
                blank=True,
                help_text="The type of input of the original file (for example video)",
                max_length=255,
                null=True,
            ),
        ),
    ]
