# Generated by Django 4.2.10 on 2024-03-11 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("indexes", "0013_alter_indexfile_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskStatus",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("task_id", models.CharField(help_text="Celery task ID", max_length=255, unique=True)),
                ("task_name", models.CharField(help_text="Name or type of the task", max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("STARTED", "Started"),
                            ("SUCCESS", "Success"),
                            ("FAILURE", "Failure"),
                            ("RETRY", "Retry"),
                            ("REVOKED", "Revoked"),
                        ],
                        default="PENDING",
                        help_text="Current status of the task",
                        max_length=50,
                    ),
                ),
                ("result", models.TextField(blank=True, help_text="Task result or error message", null=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who initiated the task",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Task Status",
                "verbose_name_plural": "Task Statuses",
                "ordering": ["-created"],
            },
        ),
    ]
